catalogue/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('produit/<categorie>/<slug>', ProduitDetail.as_view(), name='produit'),
    path('About', about, name='about'),
    path('contact', contact, name='contact'),
    path('panier', panier, name='panier'),
    path('404', error, name='error'), 
    path('ajout-au-panier/<categorie>/<slug>/', ajout_au_panier, name='ajout-au-panier'),
    path('supp-du-panier/<categorie>/<slug>/', supp_du_panier, name='supp-du-panier'),
]

e_commerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalogue.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    

catalogue/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.

CATEGORIE_CHOIX = (
    ('L', 'Legumes'),
    ('F', 'Fruits'),
    ('C', 'Cereales'),
)
LABEL_CHOIX = (
    ('S', 'Secondary'),
    ('P', 'Primary'),
    ('D', 'Danger'),
)


class Item(models.Model): #Item du catalogue
    titre = models.CharField(max_length=100)
    prix = models.FloatField()
    prix_reduit = models.IntegerField(blank=True, null=True)
    slug = models.SlugField()
    categorie = models.CharField(choices=CATEGORIE_CHOIX, max_length=1)
    label = models.CharField(choices=LABEL_CHOIX, max_length=1)
    description = models.TextField()
    image = models.ImageField(default='tt.png', upload_to='')
    def __str__(self):
        return self.titre
    
    def get_add_to_cart_url(self):
        return reverse("ajout-au-panier", kwargs={
            'categorie': self.categorie,
            'slug': self.slug
        })
        
    def get_remove_from_cart_url(self):
        return reverse("supp-du-panier", kwargs={
            'categorie': self.categorie,
            'slug': self.slug
        })
           
class Variation(models.Model): #Variation de l'item
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    nom = models.CharField(max_length=200)
    
    class Meta:
        unique_together = (
            ('item', 'nom'),
        )
    
    def __str__(self):
        return self.nom  
    
class Item_Variation(models.Model): #Variation de l'item
    variation = models.ForeignKey(Variation, on_delete=models.CASCADE)
    valeur = models.CharField(max_length=200)
    attachment = models.ImageField(upload_to='')
    
    class Meta:
        unique_together = (
            ('variation', 'valeur'),
        )
    
    def __str__(self):
        return self.valeur            

class OrderItem(models.Model): #Item de la commande
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    Ordered = models.BooleanField(default=False)
    quantity = models.IntegerField(default=1)
    def __str__(self):
        return f"{self.quantity} of {self.item.titre}"

class Order(models.Model): #Commande de l'utilisateur
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    Ordered = models.BooleanField(default=False)
    start_date = models.DateTimeField(auto_now_add=True)
    Ordered_date = models.DateTimeField()
    
    def __str__(self):
        return self.user.username

catalogue/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.utils import timezone
from django.views.generic import ListView, DetailView
from .models import *

class HomeView(ListView):
    model = Item
    template_name = 'index.html'

class ProduitDetail (DetailView):
    model = Item
    template_name = 'single-product.html'
    
    
def ajout_au_panier(request, slug, categorie):
    item = get_object_or_404(Item, slug=slug, categorie=categorie)
    order_item, created = OrderItem.objects.get_or_create(item=item, user=request.user, Ordered=False)
    order_qs = Order.objects.filter(user=request.user, Ordered=False)
    
    if order_qs.exists():
        
        order = order_qs[0]
        if order.items.filter(item__slug=item.slug).exists():
            order_item.quantity += 1
            order_item.save()
            messages.success(request, f"{item.titre} quantité mise à jour.")
            return redirect("produit", slug=slug, categorie=categorie)
            
        else:
            
            order.items.add(order_item)
            order.save()
            messages.success(request, f"{item.titre} ajouté au panier.")
            return redirect("produit", slug=slug, categorie=categorie) 
    else:
        
        ordered_date = timezone.now()
        order = Order.objects.create(user=request.user, Ordered=False, Ordered_date=ordered_date)
        order.items.add(order_item)
        order.save()
        messages.success(request, f"{item.titre} ajouté au panier.")
        return redirect("produit", slug=slug, categorie=categorie)

def supp_du_panier(request, slug, categorie):
    item = get_object_or_404(Item, slug=slug, categorie=categorie)
    order_item, created = OrderItem.objects.get_or_create(item=item, user=request.user, Ordered=False)
    order_qs = Order.objects.filter(user=request.user, Ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug=item.slug).exists():
            order.items.remove(order_item)
            order.save()
            messages.success(request, f"{item.titre} à été supprimé du panier.")
            return redirect("produit", slug=slug, categorie=categorie)
        else:
            messages.info(request, f"{item.titre} n'est pas dans le panier.")
            return redirect("produit", slug=slug, categorie=categorie) 
    else:
        messages.info(request, "Vous n'avez pas de commande en cours!")
        return redirect("produit", slug=slug, categorie=categorie) 
    
def about(request):
    return render(request, 'about.html')

def contact(request):
    return render(request, 'contact.html')

def panier(request):
    return render(request, 'cart.html')

def error(request):
    return render(request, '404.html')

templates/about.html
{% extends "master.html" %}

{% block color-About %}
	style="color: #F28123;"
{% endblock color-About %}

{% block content %}
{% load static %}

	<!-- breadcrumb-section -->
	<div class="breadcrumb-section breadcrumb-bg">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 offset-lg-2 text-center">
					<div class="breadcrumb-text">
						<p>We sale fresh fruits</p>
						<h1>About Us</h1>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end breadcrumb section -->

	<!-- featured section -->
	<div class="feature-bg">
		<div class="container">
			<div class="row">
				<div class="col-lg-7">
					<div class="featured-text">
						<h2 class="pb-3">Why <span class="orange-text">Fruitkha</span></h2>
						<div class="row">
							<div class="col-lg-6 col-md-6 mb-4 mb-md-5">
								<div class="list-box d-flex">
									<div class="list-icon">
										<i class="fas fa-shipping-fast"></i>
									</div>
									<div class="content">
										<h3>Home Delivery</h3>
										<p>sit voluptatem accusantium dolore mque laudantium, totam rem aperiam, eaque ipsa quae ab illo.</p>
									</div>
								</div>
							</div>
							<div class="col-lg-6 col-md-6 mb-5 mb-md-5">
								<div class="list-box d-flex">
									<div class="list-icon">
										<i class="fas fa-money-bill-alt"></i>
									</div>
									<div class="content">
										<h3>Best Price</h3>
										<p>sit voluptatem accusantium dolore mque laudantium, totam rem aperiam, eaque ipsa quae ab illo.</p>
									</div>
								</div>
							</div>
							<div class="col-lg-6 col-md-6 mb-5 mb-md-5">
								<div class="list-box d-flex">
									<div class="list-icon">
										<i class="fas fa-briefcase"></i>
									</div>
									<div class="content">
										<h3>Custom Box</h3>
										<p>sit voluptatem accusantium dolore mque laudantium, totam rem aperiam, eaque ipsa quae ab illo.</p>
									</div>
								</div>
							</div>
							<div class="col-lg-6 col-md-6">
								<div class="list-box d-flex">
									<div class="list-icon">
										<i class="fas fa-sync-alt"></i>
									</div>
									<div class="content">
										<h3>Quick Refund</h3>
										<p>sit voluptatem accusantium dolore mque laudantium, totam rem aperiam, eaque ipsa quae ab illo.</p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end featured section -->

	<!-- shop banner -->
	<section class="shop-banner">
    	<div class="container">
        	<h3>December sale is on! <br> with big <span class="orange-text">Discount...</span></h3>
            <div class="sale-percent"><span>Sale! <br> Upto</span>50% <span>off</span></div>
            <a href="shop.html" class="cart-btn btn-lg">Shop Now</a>
        </div>
    </section>
	<!-- end shop banner -->

	<!-- team section -->
	<div class="mt-150">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 offset-lg-2 text-center">
					<div class="section-title">
						<h3>Our <span class="orange-text">Team</span></h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid, fuga quas itaque eveniet beatae optio.</p>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-4 col-md-6">
					<div class="single-team-item">
						<div class="team-bg team-bg-1"></div>
						<h4>Jimmy Doe <span>Farmer</span></h4>
						<ul class="social-link-team">
							<li><a href="#" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-twitter"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-instagram"></i></a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-4 col-md-6">
					<div class="single-team-item">
						<div class="team-bg team-bg-2"></div>
						<h4>Marry Doe <span>Farmer</span></h4>
						<ul class="social-link-team">
							<li><a href="#" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-twitter"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-instagram"></i></a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-4 col-md-6 offset-md-3 offset-lg-0">
					<div class="single-team-item">
						<div class="team-bg team-bg-3"></div>
						<h4>Simon Joe <span>Farmer</span></h4>
						<ul class="social-link-team">
							<li><a href="#" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-twitter"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-instagram"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end team section -->

	<!-- testimonail-section -->
	<div class="testimonail-section mt-80 mb-150">
		<div class="container">
			<div class="row">
				<div class="col-lg-10 offset-lg-1 text-center">
					<div class="testimonial-sliders">
						<div class="single-testimonial-slider">
							<div class="client-avater">
								<img src="assets/img/avaters/avatar1.png" alt="">
							</div>
							<div class="client-meta">
								<h3>Saira Hakim <span>Local shop owner</span></h3>
								<p class="testimonial-body">
									" Sed ut perspiciatis unde omnis iste natus error veritatis et  quasi architecto beatae vitae dict eaque ipsa quae ab illo inventore Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium "
								</p>
								<div class="last-icon">
									<i class="fas fa-quote-right"></i>
								</div>
							</div>
						</div>
						<div class="single-testimonial-slider">
							<div class="client-avater">
								<img src="assets/img/avaters/avatar2.png" alt="">
							</div>
							<div class="client-meta">
								<h3>David Niph <span>Local shop owner</span></h3>
								<p class="testimonial-body">
									" Sed ut perspiciatis unde omnis iste natus error veritatis et  quasi architecto beatae vitae dict eaque ipsa quae ab illo inventore Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium "
								</p>
								<div class="last-icon">
									<i class="fas fa-quote-right"></i>
								</div>
							</div>
						</div>
						<div class="single-testimonial-slider">
							<div class="client-avater">
								<img src="assets/img/avaters/avatar3.png" alt="">
							</div>
							<div class="client-meta">
								<h3>Jacob Sikim <span>Local shop owner</span></h3>
								<p class="testimonial-body">
									" Sed ut perspiciatis unde omnis iste natus error veritatis et  quasi architecto beatae vitae dict eaque ipsa quae ab illo inventore Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium "
								</p>
								<div class="last-icon">
									<i class="fas fa-quote-right"></i>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end testimonail-section -->

{% endblock %}

templates/cart.html
{% extends "master.html" %}


{% block color-panier %}
	style="color: #F28123;"
{% endblock color-panier %}

{% block content %}
{% load static %}

<!-- breadcrumb-section -->
<div class="breadcrumb-section breadcrumb-bg">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 offset-lg-2 text-center">
				<div class="breadcrumb-text">
					<p>Frais et Organic</p>
					<h1>Panier</h1>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- end breadcrumb section -->

<!-- cart -->
<div class="cart-section mt-150 mb-150">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 col-md-12">
				<div class="cart-table-wrap">
					<table class="cart-table">
						<thead class="cart-table-head">
							<tr class="table-head-row">
								<th class="product-remove"></th>
								<th class="product-image">Product Image</th>
								<th class="product-name">Name</th>
								<th class="product-price">Price</th>
								<th class="product-quantity">Quantity</th>
								<th class="product-total">Total</th>
							</tr>
						</thead>
						<tbody>
							<tr class="table-body-row">
								<td class="product-remove"><a href="#"><i class="far fa-window-close"></i></a></td>
								<td class="product-image"><img src={% static "img/products/product-img-1.jpg" %} alt=""></td>
								<td class="product-name">Strawberry</td>
								<td class="product-price">$85</td>
								<td class="product-quantity"><input type="number" placeholder="0"></td>
								<td class="product-total">1</td>
							</tr>
							<tr class="table-body-row">
								<td class="product-remove"><a href="#"><i class="far fa-window-close"></i></a></td>
								<td class="product-image"><img src={% static "img/products/product-img-2.jpg" %} alt=""></td>
								<td class="product-name">Berry</td>
								<td class="product-price">$70</td>
								<td class="product-quantity"><input type="number" placeholder="0"></td>
								<td class="product-total">1</td>
							</tr>
							<tr class="table-body-row">
								<td class="product-remove"><a href="#"><i class="far fa-window-close"></i></a></td>
								<td class="product-image"><img src={% static "img/products/product-img-3.jpg" %} alt=""></td>
								<td class="product-name">Lemon</td>
								<td class="product-price">$35</td>
								<td class="product-quantity"><input type="number" placeholder="0"></td>
								<td class="product-total">1</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>

			<div class="col-lg-4">
				<div class="total-section">
					<table class="total-table">
						<thead class="total-table-head">
							<tr class="table-total-row">
								<th>Total</th>
								<th>Price</th>
							</tr>
						</thead>
						<tbody>
							<tr class="total-data">
								<td><strong>Subtotal: </strong></td>
								<td>$500</td>
							</tr>
							<tr class="total-data">
								<td><strong>Shipping: </strong></td>
								<td>$45</td>
							</tr>
							<tr class="total-data">
								<td><strong>Total: </strong></td>
								<td>$545</td>
							</tr>
						</tbody>
					</table>
					<div class="cart-buttons">
						<a href="cart.html" class="boxed-btn">Update Cart</a>
						<a href="checkout.html" class="boxed-btn black">Check Out</a>
					</div>
				</div>

				<div class="coupon-section">
					<h3>Apply Coupon</h3>
					<div class="coupon-form-wrap">
						<form action="index.html">
							<p><input type="text" placeholder="Coupon"></p>
							<p><input type="submit" value="Apply"></p>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- end cart -->

{% endblock %}

templates/contact.html
{% extends "master.html" %}

{% block color-contact %}
	style="color: #F28123;"
{% endblock color-contact %}

{% block content %}
  
	<!-- breadcrumb-section -->
	<div class="breadcrumb-section breadcrumb-bg">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 offset-lg-2 text-center">
					<div class="breadcrumb-text">
						<p>Get 24/7 Support</p>
						<h1>Contact us</h1>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end breadcrumb section -->

	<!-- contact form -->
	<div class="contact-from-section mt-150 mb-150">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 mb-5 mb-lg-0">
					<div class="form-title">
						<h2>Have you any question?</h2>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur, ratione! Laboriosam est, assumenda. Perferendis, quo alias quaerat aliquid. Corporis ipsum minus voluptate? Dolore, esse natus!</p>
					</div>
				 	<div id="form_status"></div>
					<div class="contact-form">
						<form type="POST" id="fruitkha-contact" onSubmit="return valid_datas( this );">
							<p>
								<input type="text" placeholder="Name" name="name" id="name">
								<input type="email" placeholder="Email" name="email" id="email">
							</p>
							<p>
								<input type="tel" placeholder="Phone" name="phone" id="phone">
								<input type="text" placeholder="Subject" name="subject" id="subject">
							</p>
							<p><textarea name="message" id="message" cols="30" rows="10" placeholder="Message"></textarea></p>
							<input type="hidden" name="token" value="FsWga4&@f6aw" />
							<p><input type="submit" value="Submit"></p>
						</form>
					</div>
				</div>
				<div class="col-lg-4">
					<div class="contact-form-wrap">
						<div class="contact-form-box">
							<h4><i class="fas fa-map"></i> Shop Address</h4>
							<p>34/8, East Hukupara <br> Gifirtok, Sadan. <br> Country Name</p>
						</div>
						<div class="contact-form-box">
							<h4><i class="far fa-clock"></i> Shop Hours</h4>
							<p>MON - FRIDAY: 8 to 9 PM <br> SAT - SUN: 10 to 8 PM </p>
						</div>
						<div class="contact-form-box">
							<h4><i class="fas fa-address-book"></i> Contact</h4>
							<p>Phone: +00 111 222 3333 <br> Email: support@fruitkha.com</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end contact form -->

{% endblock content %}

templates/login/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="fonts/icomoon/style.css">

    <link rel="stylesheet" href="css/owl.carousel.min.css">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    
    <!-- Style -->
    <link rel="stylesheet" href="css/style.css">

    <title>Login #2</title>
  </head>
  <body>
  

  <div class="d-lg-flex half">
    <div class="bg order-1 order-md-2" style="background-image: url('images/bg_1.jpg');"></div>
    <div class="contents order-2 order-md-1">

      <div class="container">
        <div class="row align-items-center justify-content-center">
          <div class="col-md-7">
            <h3>Login to <strong>Colorlib</strong></h3>
            <p class="mb-4">Lorem ipsum dolor sit amet elit. Sapiente sit aut eos consectetur adipisicing.</p>
            <form action="#" method="post">
              <div class="form-group first">
                <label for="username">Username</label>
                <input type="text" class="form-control" placeholder="your-email@gmail.com" id="username">
              </div>
              <div class="form-group last mb-3">
                <label for="password">Password</label>
                <input type="password" class="form-control" placeholder="Your Password" id="password">
              </div>
              
              <div class="d-flex mb-5 align-items-center">
                <label class="control control--checkbox mb-0"><span class="caption">Remember me</span>
                  <input type="checkbox" checked="checked"/>
                  <div class="control__indicator"></div>
                </label>
                <span class="ml-auto"><a href="#" class="forgot-pass">Forgot Password</a></span> 
              </div>

              <input type="submit" value="Log In" class="btn btn-block btn-primary">

            </form>
          </div>
        </div>
      </div>
    </div>

    
  </div>
    
    

    <script src="js/jquery-3.3.1.min.js"></script>
    <script src="js/popper.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/main.js"></script>
  </body>
</html>

templates/login/main.html
<a href="https://colorlib.com/wp/templates/"><img src="https://colorlib.com/wp/wp-content/uploads/sites/2/colorlib-push-logo.png" alt="Colorlib logo"></a>
<h1 style="text-align:center;">Thank you for using our template!</h1>
<p style="text-align:center;">For more awesome templates please visit <strong><a href="https://colorlib.com/wp/templates/">Colorlib</a></strong>.</p>

<style>
img {
  margin: 0 auto;
  display: block;
  margin-top: 20%;
}
</style>

templates/single-product.html
{% extends "master.html" %}

{% block color-cat %}
style="color: #F28123;"
{% endblock color-cat %}

{% block content %}
{% load static %}

	
<!-- breadcrumb-section -->
<div class="breadcrumb-section breadcrumb-bg">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 offset-lg-2 text-center">
				<div class="breadcrumb-text">
					<p>See more Details</p>
					<h1>Single Product</h1>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- end breadcrumb section -->


{% if messages %}
	<div class="single-product mb-150" style="margin-top: 50px">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 offset-lg-2 text-center">
					<div class="section-title">	
						{% for message in messages %}
							<div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
								{{ message }}
								<button type="button" class="close" data-dismissible="alert" aria-label="close">
									<span aria-hidden="true">&times;</span>
								</button>
							</div>
						{% endfor %}
					</div>
				</div>
			</div>
		</div>
	</div>
{% endif %}



<!-- single product -->
<div class="single-product mt-150 mb-150">
	<div class="container">
		<div class="row">
			<div class="col-md-5">
				<div class="single-product-img">
					<img style="width: 100%; height: 100%;" src={{object.image.url}} alt="">
				</div>
			</div>
			<div class="col-md-7">
				<div class="single-product-content">
					<h3>{{object.titre}}</h3>
					<p class="single-product-pricing"><span>Par Kg</span> {{object.prix}} F CFA </p>
					<p>{{object.description}}</p>
					<div class="single-product-form">
						<form action="index.html">
							<input type="number" placeholder="0">
						</form>
						<a href="{{object.get_add_to_cart_url}}" class="cart-btn"><i class="fas fa-shopping-cart"></i> Ajouter au panier</a> &nbsp;
						<a href="{{object.get_remove_from_cart_url}}" class="cart-btn"><i class="fas fa-trash-alt"></i> Suppression du panier</a>
						<p><strong>Categories: </strong>{{object.get_categorie_display}}</p>
					</div>
					<h4>Share:</h4>
					<ul class="product-share">
						<li><a href=""><i class="fab fa-facebook-f"></i></a></li>
						<li><a href=""><i class="fab fa-twitter"></i></a></li>
						<li><a href=""><i class="fab fa-google-plus-g"></i></a></li>
						<li><a href=""><i class="fab fa-linkedin"></i></a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- end single product -->

<!-- more products -->
<div class="more-products mb-150">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 offset-lg-2 text-center">
				<div class="section-title">	
					<h3><span class="orange-text">Related</span> Products</h3>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid, fuga quas itaque eveniet beatae optio.</p>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-4 col-md-6 text-center">
				<div class="single-product-item">
					<div class="product-image">
						<a href="single-product.html"><img src={% static "img/products/product-img-1.jpg" %} alt=""></a>
					</div>
					<h3>Strawberry</h3>
					<p class="product-price"><span>Per Kg</span> 85$ </p>
					<a href="cart.html" class="cart-btn"><i class="fas fa-shopping-cart"></i> Add to Cart</a>
				</div>
			</div>
			<div class="col-lg-4 col-md-6 text-center">
				<div class="single-product-item">
					<div class="product-image">
						<a href="single-product.html"><img src={% static "img/products/product-img-2.jpg" %} alt=""></a>
					</div>
					<h3>Berry</h3>
					<p class="product-price"><span>Per Kg</span> 70$ </p>
					<a href="cart.html" class="cart-btn"><i class="fas fa-shopping-cart"></i> Add to Cart</a>
				</div>
			</div>
			<div class="col-lg-4 col-md-6 offset-lg-0 offset-md-3 text-center">
				<div class="single-product-item">
					<div class="product-image">
						<a href="single-product.html"><img src={% static "img/products/product-img-3.jpg" %} alt=""></a>
					</div>
					<h3>Lemon</h3>
					<p class="product-price"><span>Per Kg</span> 35$ </p>
					<a href="cart.html" class="cart-btn"><i class="fas fa-shopping-cart"></i> Add to Cart</a>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- end more products -->


{% endblock %}